global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2

scrape_configs:
- job_name: node_exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - node_exporter:9100

- job_name: nginx_exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - nginx_exporter:9113

- job_name: mysql_exporter
  metrics_path: /metrics
  params:
  static_configs:
  - targets:
    - mysql_exporter:9104
  #relabel_configs:
  #  - source_labels: [__address__]
  #    target_label: __param_target
  #  - source_labels: [__param_target]
  #    target_label: instance
  #  - target_label: __address__
  #    # The mysqld_exporter host:port
  #    replacement: localhost:9104