CREATE USER IF NOT EXISTS 'exporter'@'172.16.16.23' IDENTIFIED BY 'exporter_pass' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'172.16.16.23';
FLUSH PRIVILEGES;

